modLoader="javafml"
loaderVersion="[43,)"
license="MIT"
issueTrackerURL="https://github.com/MaroonShaded/GildedArmor/issues"
[[mods]]
    modId="gildedarmor"
    version="${file.jarVersion}"
    displayName="Gilded Armor"
    updateJSONURL="https://raw.githubusercontent.com/MaroonShaded/maroonshaded.github.io/main/projects/mods/gildedarmor/update.json"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/gildedarmor"
    logoFile="gildedarmor.png"
    credits="Thanks to SystemZee for the idea and all the translators and contributors!"
    authors="MaroonShaded"
    description="Gilded armor makes piglins peaceful while you're using a stronger material."

[[dependencies.gildedarmor]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.gildedarmor]]
    modId="minecraft"
    mandatory=true
    versionRange="1.19.2"
    ordering="NONE"
    side="BOTH"

[modproperties.gildedarmor]
    catalogueItemIcon="gildedarmor:gilded_netherite_chestplate"
