modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
issueTrackerURL="https://github.com/MaroonShaded/GildedArmor/issues"
[[mods]]
    modId="gildedarmor"
    version="${file.jarVersion}"
    displayName="Gilded Armor"
    updateJSONURL="https://raw.githubusercontent.com/MaroonShaded/GildedArmor/master/update.json"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/gildedarmor"
    logoFile="gildedarmor.png"
    credits="Thanks to SystemZee for the idea! kirechka, randomnickname2137, Jacobs-Develop, Moze-Yosel, and zeedif for translations!"
    authors="MaroonShaded"
    description="Gilded armor makes piglins peaceful while you're using a stronger material."

[[dependencies.gildedarmor]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.gildedarmor]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
